[package]
name = "juno"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
regex = "1.11.1"
rfd = "0.15.2"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = "1.43.0"
